/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/configuration/MessageSourceConfiguration.p.vm.java
 */
package br.com.aj2.configuration;

import org.springframework.context.MessageSource;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;

@Configuration
public class MessageSourceConfiguration {
    /**
     * Base message source to handle internationalization
     */
    @Bean
    public MessageSource messageSource() {
        ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
        messageSource.setFallbackToSystemLocale(false);
        messageSource.setUseCodeAsDefaultMessage(true);
        messageSource.setDefaultEncoding("UTF-8");
        messageSource.setBasenames( // main resources
                "classpath:/localization/application", //
                "classpath:/localization/messages", //
                // generated domain resources
                "classpath:/localization/domain/Account", //
                "classpath:/localization/domain/Agenda", //
                "classpath:/localization/domain/Cliente", //
                "classpath:/localization/domain/Empresa", //
                "classpath:/localization/domain/Equipamentos", //
                "classpath:/localization/domain/Estudios", //
                "classpath:/localization/domain/Grupocliente", //
                "classpath:/localization/domain/ItensOs", //
                "classpath:/localization/domain/Lancamentos", //
                "classpath:/localization/domain/Locacao", //
                "classpath:/localization/domain/Os", //
                "classpath:/localization/domain/Produtor", //
                "classpath:/localization/domain/Role", //
                "classpath:/localization/domain/Servicos", //
                "classpath:/localization/domain/TipoEquipamento", //
                // pages
                "classpath:/localization/pages/home", //
                "classpath:/localization/pages/login", //
                "classpath:/localization/pages/concurrentModificationResolution", //
                // default spring security messages
                "classpath:org/springframework/security/messages", //
                //  our bean validation messages
                "classpath:ValidationMessages", //
                // default conversion messages
                "classpath:javax/faces/Messages", //
                // default bean validation messages 
                "classpath:org/hibernate/validator/ValidationMessages");
        return messageSource;
    }
}
