/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/support/GenericSearchForm.p.vm.java
 */
package br.com.aj2.web.domain.support;

import java.io.Serializable;
import javax.inject.Inject;
import javax.annotation.PostConstruct;

import br.com.aj2.domain.Identifiable;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.web.conversation.Conversation;
import br.com.aj2.web.conversation.ConversationManager;

/**
 * Base Search Form for JPA entities.
 */
public abstract class GenericSearchForm<E extends Identifiable<PK>, PK extends Serializable, F extends GenericSearchForm<E, PK, F>> extends CommonAction<E>
        implements Serializable {
    private static final long serialVersionUID = 1L;

    @Inject
    private transient ConversationManager conversationManager;

    @SuppressWarnings("unchecked")
    @PostConstruct
    public void init() {
        Conversation currentConversation = conversationManager.getCurrentConversation();
        if (currentConversation != null && currentConversation.getBean(getPrefilledFormName()) != null) {
            resetWithOther((F) currentConversation.getBean(getPrefilledFormName()));
        }
    }

    public String getPrefilledFormName() {
        return "_" + this.getClass().getName() + "_prefilled_";
    }

    /**
     * Return the entity example used in this search form.
     */
    protected abstract E getEntity();

    /**
     * Convert all the search inputs into a @{link SearchParameters}. 
     */
    public abstract SearchParameters toSearchParameters();

    // Reset related

    public abstract F newInstance();

    public abstract void resetWithOther(F other);

    public void reset() {
        resetWithOther(newInstance());
    }
}
