/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/Repository.e.vm.java
 */
package br.com.aj2.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import br.com.aj2.dao.AgendaDao;
import br.com.aj2.domain.Agenda;
import br.com.aj2.repository.support.GenericRepository;

/**
 * Note: you may use multiple DAO from this layer.
 */
@Named
@Singleton
public class AgendaRepository extends GenericRepository<Agenda, Integer> {

    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(AgendaRepository.class);

    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected AgendaRepository() {
        super();
    }

    @Inject
    public AgendaRepository(AgendaDao agendaDao) {
        super(agendaDao);
    }

    @Override
    public Agenda getNew() {
        return new Agenda();
    }

    @Override
    public Agenda getNewWithDefaults() {
        Agenda result = getNew();
        result.initDefaultValues();
        return result;
    }
}