/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/conversation/ConcurrentModificationResolver.p.vm.java
 */
package br.com.aj2.web.conversation;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import br.com.aj2.web.conversation.ConversationManager;

@Named
@Singleton
public class ConcurrentModificationResolver {

    @Inject
    private ConversationManager conversationManager;

    public String refresh() {
        return conversationManager.getCurrentConversation().getCurrentContext().getCallBack().ok(null);
    }

    public String discard() {
        conversationManager.endCurrentConversation();
        return "/home.faces?faces-redirect=true";
    }
}
