/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Enum.enum.vm.java
 */
package br.com.aj2.enumTypes;

import br.com.aj2.util.ResourcesUtil;

public enum UF {
    AC, AL, AM, AP, BA, CE, DF, ES, GO, MA, MG, MT, MS, PA, PB, PE, PI, PR, RJ, RN, RO, RR, RS, SC, SE, SP, TO;

    public String getLabel() {
        return ResourcesUtil.getInstance().getProperty("UF_" + name());
    }
}