/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/service/EnvironmentService.p.vm.java
 */
package br.com.aj2.service;

import static br.com.aj2.service.EnvironmentService.Environment.Development;
import static br.com.aj2.service.EnvironmentService.Environment.Integration;
import static br.com.aj2.service.EnvironmentService.Environment.Production;
import static br.com.aj2.service.EnvironmentService.Environment.toEnvironment;
import static org.apache.commons.lang.StringUtils.trimToEmpty;

import javax.inject.Named;

import org.springframework.beans.factory.annotation.Value;

@Named
public class EnvironmentService {
    @Value("${env_name:development}")
    private String environmentName;

    public enum Environment {
        Development, Integration, Production;
        boolean is(String value) {
            return name().equalsIgnoreCase(trimToEmpty(value));
        }

        public static Environment toEnvironment(String value) {
            for (Environment environment : values()) {
                if (environment.is(value)) {
                    return environment;
                }
            }
            return Development;
        }
    }

    public boolean isDevelopment() {
        return Development.is(environmentName);
    }

    public boolean isIntegration() {
        return Integration.is(environmentName);
    }

    public boolean isProduction() {
        return Production.is(environmentName);
    }

    public Environment getEnvironment() {
        return toEnvironment(environmentName);
    }
}
