/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/printer/Printer.e.vm.java
 */
package br.com.aj2.printer;

import java.util.Locale;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.domain.Os;
import br.com.aj2.printer.DiscoverablePrinter;

/**
 * {@link org.springframework.format.Printer} for {@link Os} 
 *
 * @see org.springframework.format.Printer
 * @see DiscoverablePrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class OsPrinter extends DiscoverablePrinter<Os> {
    public OsPrinter() {
        super(Os.class);
    }

    @Override
    public String print(Os os, Locale locale) {
        if (os == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        
        if (os.getCliente() != null) {
            appendIfNotEmpty(ret, os.getCliente().getNome());
        }
        
        if (os.getProdutor() != null) {
            appendIfNotEmpty(ret, os.getProdutor().getNome());
        }
        
        appendIfNotEmpty(ret, os.getLastModificationAuthor());
        return ret.toString();
    }
}