/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/Repository.e.vm.java
 */
package br.com.aj2.repository;

import static org.apache.commons.lang.StringUtils.isBlank;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.transaction.annotation.Transactional;
import br.com.aj2.dao.ClienteDao;
import br.com.aj2.domain.Cliente;
import br.com.aj2.repository.support.GenericRepository;

/**
 * Note: you may use multiple DAO from this layer.
 */
@Named
@Singleton
public class ClienteRepository extends GenericRepository<Cliente, Integer> {

    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(ClienteRepository.class);

    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected ClienteRepository() {
        super();
    }

    @Inject
    public ClienteRepository(ClienteDao clienteDao) {
        super(clienteDao);
    }

    @Override
    public Cliente getNew() {
        return new Cliente();
    }

    @Override
    public Cliente getNewWithDefaults() {
        Cliente result = getNew();
        result.initDefaultValues();
        return result;
    }

    @Override
    @Transactional(readOnly = true)
    public Cliente get(Cliente model) {
        if (model == null) {
            return null;
        }

        if (model.isIdSet()) {
            return super.get(model);
        }
        if (isBlank(model.getCpfCnpj())) {
            Cliente result = getByCpfCnpj(model.getCpfCnpj());
            if (result != null) {
                return result;
            }
        }
        if (isBlank(model.getEmail())) {
            Cliente result = getByEmail(model.getEmail());
            if (result != null) {
                return result;
            }
        }

        return null;
    }

    /**
     * Return the persistent instance of {@link Cliente} with the given unique property value cpfCnpj,
     * or null if there is no such persistent instance.
     *
     * @param cpfCnpj the unique value
     * @return the corresponding {@link Cliente} persistent instance or null
     */
    @Transactional(readOnly = true)
    public Cliente getByCpfCnpj(String cpfCnpj) {
        return findUniqueOrNone(new Cliente().cpfCnpj(cpfCnpj));
    }

    /**
     * Delete a {@link Cliente} using the unique column cpfCnpj
     *
     * @param cpfCnpj the unique value
     */
    @Transactional
    public void deleteByCpfCnpj(String cpfCnpj) {
        delete(getByCpfCnpj(cpfCnpj));
    }

    /**
     * Return the persistent instance of {@link Cliente} with the given unique property value email,
     * or null if there is no such persistent instance.
     *
     * @param email the unique value
     * @return the corresponding {@link Cliente} persistent instance or null
     */
    @Transactional(readOnly = true)
    public Cliente getByEmail(String email) {
        return findUniqueOrNone(new Cliente().email(email));
    }

    /**
     * Delete a {@link Cliente} using the unique column email
     *
     * @param email the unique value
     */
    @Transactional
    public void deleteByEmail(String email) {
        delete(getByEmail(email));
    }
}