/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/Repository.e.vm.java
 */
package br.com.aj2.repository;

import static org.apache.commons.lang.StringUtils.isBlank;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.transaction.annotation.Transactional;
import br.com.aj2.dao.GrupoclienteDao;
import br.com.aj2.domain.Grupocliente;
import br.com.aj2.repository.support.GenericRepository;

/**
 * Note: you may use multiple DAO from this layer.
 */
@Named
@Singleton
public class GrupoclienteRepository extends GenericRepository<Grupocliente, Integer> {

    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(GrupoclienteRepository.class);

    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected GrupoclienteRepository() {
        super();
    }

    @Inject
    public GrupoclienteRepository(GrupoclienteDao grupoclienteDao) {
        super(grupoclienteDao);
    }

    @Override
    public Grupocliente getNew() {
        return new Grupocliente();
    }

    @Override
    public Grupocliente getNewWithDefaults() {
        Grupocliente result = getNew();
        result.initDefaultValues();
        return result;
    }

    @Override
    @Transactional(readOnly = true)
    public Grupocliente get(Grupocliente model) {
        if (model == null) {
            return null;
        }

        if (model.isIdSet()) {
            return super.get(model);
        }
        if (isBlank(model.getNome())) {
            Grupocliente result = getByNome(model.getNome());
            if (result != null) {
                return result;
            }
        }

        return null;
    }

    /**
     * Return the persistent instance of {@link Grupocliente} with the given unique property value nome,
     * or null if there is no such persistent instance.
     *
     * @param nome the unique value
     * @return the corresponding {@link Grupocliente} persistent instance or null
     */
    @Transactional(readOnly = true)
    public Grupocliente getByNome(String nome) {
        return findUniqueOrNone(new Grupocliente().nome(nome));
    }

    /**
     * Delete a {@link Grupocliente} using the unique column nome
     *
     * @param nome the unique value
     */
    @Transactional
    public void deleteByNome(String nome) {
        delete(getByNome(nome));
    }
}