/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/Repository.e.vm.java
 */
package br.com.aj2.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.transaction.annotation.Transactional;
import br.com.aj2.dao.ItensOsDao;
import br.com.aj2.domain.ItensOs;
import br.com.aj2.repository.support.GenericRepository;

/**
 * Note: you may use multiple DAO from this layer.
 */
@Named
@Singleton
public class ItensOsRepository extends GenericRepository<ItensOs, Integer> {

    private static final Logger log = LoggerFactory.getLogger(ItensOsRepository.class);

    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected ItensOsRepository() {
        super();
    }

    @Inject
    public ItensOsRepository(ItensOsDao itensOsDao) {
        super(itensOsDao);
    }

    @Override
    public ItensOs getNew() {
        return new ItensOs();
    }

    @Override
    public ItensOs getNewWithDefaults() {
        ItensOs result = getNew();
        result.initDefaultValues();
        return result;
    }

    @Override
    @Transactional
    public void delete(ItensOs itensOs) {
        if (itensOs == null) {
            log.debug("Skipping deletion for null model!");
            return;
        }

        // remove the reference from the associated itensOss
        if (itensOs.getOs() != null) {
            itensOs.getOs().removeItensOs(itensOs);
        }

        super.delete(itensOs);
    }
}