/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Cliente;
import br.com.aj2.domain.Cliente_;
import br.com.aj2.repository.ClienteRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.ClientePermission;

/**
 * Stateless controller for {@link Cliente} conversation start. 
 */
@Named
@Singleton
public class ClienteController extends GenericController<Cliente, Integer> {
    private static final String editUri = "/domain/clienteEdit.faces";
    private static final String selectUri = "/domain/clienteSelect.faces";

    @Inject
    public ClienteController(ClienteRepository clienteRepository, ClientePermission clientePermission) {
        super(clienteRepository, clientePermission, selectUri, editUri);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        searchParameters.orderBy(Cliente_.cpfCnpj);
        return searchParameters;
    }

}