/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Estudios;
import br.com.aj2.domain.Estudios_;
import br.com.aj2.repository.EstudiosRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.EstudiosPermission;

/**
 * Stateless controller for {@link Estudios} conversation start. 
 */
@Named
@Singleton
public class EstudiosController extends GenericController<Estudios, Integer> {
    private static final String editUri = "/domain/estudiosEdit.faces";
    private static final String selectUri = "/domain/estudiosSelect.faces";

    @Inject
    public EstudiosController(EstudiosRepository estudiosRepository, EstudiosPermission estudiosPermission) {
        super(estudiosRepository, estudiosPermission, selectUri, editUri);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        searchParameters.orderBy(Estudios_.nome);
        return searchParameters;
    }

}