/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package br.com.aj2.web.domain;

import static br.com.aj2.dao.support.PropertySelector.newPropertySelector;
import javax.inject.Named;
import br.com.aj2.dao.support.PropertySelector;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Estudios;
import br.com.aj2.domain.Estudios_;
import br.com.aj2.web.domain.support.GenericSearchForm;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Estudios}.
 * It exposes a {@link Estudios} instance so it can be used in search by Example query.
 */
@Named
@ConversationContextScoped
public class EstudiosSearchForm extends GenericSearchForm<Estudios, Integer, EstudiosSearchForm> {
    private static final long serialVersionUID = 1L;

    protected Estudios estudios = new Estudios();
    protected PropertySelector<Estudios, String> nomeSelector = newPropertySelector(Estudios_.nome);
    protected PropertySelector<Estudios, Boolean> ativoSelector = newPropertySelector(Estudios_.ativo);

    public Estudios getEstudios() {
        return estudios;
    }

    @Override
    protected Estudios getEntity() {
        return getEstudios();
    }

    @Override
    public EstudiosSearchForm newInstance() {
        return new EstudiosSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        return new SearchParameters() //
                .anywhere() //
                .property(nomeSelector) //
                .property(ativoSelector) //
        ;
    }

    @Override
    public void resetWithOther(EstudiosSearchForm other) {
        this.estudios = other.getEstudios();
        this.nomeSelector = other.getNomeSelector();
        this.ativoSelector = other.getAtivoSelector();
    }

    // Property selectors
    public PropertySelector<Estudios, String> getNomeSelector() {
        return nomeSelector;
    }

    public PropertySelector<Estudios, Boolean> getAtivoSelector() {
        return ativoSelector;
    }
}
