/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Estudios;
import br.com.aj2.domain.Estudios_;
import br.com.aj2.repository.EstudiosRepository;
import br.com.aj2.web.converter.EstudiosJsfConverter;
import br.com.aj2.web.domain.support.GenericLazyDataModel;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Estudios}
 */
@Named
@ConversationContextScoped
public class EstudiosLazyDataModel extends GenericLazyDataModel<Estudios, Integer, EstudiosSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public EstudiosLazyDataModel(EstudiosRepository estudiosRepository, EstudiosJsfConverter estudiosConverter, EstudiosController estudiosController,
            EstudiosSearchForm estudiosSearchForm) {
        super(estudiosRepository, estudiosConverter, estudiosController, estudiosSearchForm);
    }

    @Override
    protected void defaultOrder(SearchParameters sp) {
        sp.orderBy(Estudios_.nome);
    }
}