/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Grupocliente;
import br.com.aj2.domain.Grupocliente_;
import br.com.aj2.repository.GrupoclienteRepository;
import br.com.aj2.web.converter.GrupoclienteJsfConverter;
import br.com.aj2.web.domain.support.GenericLazyDataModel;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Grupocliente}
 */
@Named
@ConversationContextScoped
public class GrupoclienteLazyDataModel extends GenericLazyDataModel<Grupocliente, Integer, GrupoclienteSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public GrupoclienteLazyDataModel(GrupoclienteRepository grupoclienteRepository, GrupoclienteJsfConverter grupoclienteConverter,
            GrupoclienteController grupoclienteController, GrupoclienteSearchForm grupoclienteSearchForm) {
        super(grupoclienteRepository, grupoclienteConverter, grupoclienteController, grupoclienteSearchForm);
    }

    @Override
    protected void defaultOrder(SearchParameters sp) {
        sp.orderBy(Grupocliente_.nome);
    }
}