/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;
import br.com.aj2.domain.Cliente;
import br.com.aj2.domain.Grupocliente;
import br.com.aj2.repository.GrupoclienteRepository;
import br.com.aj2.web.domain.ClienteController;
import br.com.aj2.web.domain.GrupoclienteGraphLoader;
import br.com.aj2.web.domain.support.GenericEditForm;
import br.com.aj2.web.domain.support.GenericToOneAssociation;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Grupocliente}.
 */
@Named
@ConversationContextScoped
public class GrupoclienteEditForm extends GenericEditForm<Grupocliente, Integer> {
    @Inject
    protected ClienteController clienteController;
    protected GenericToOneAssociation<Cliente, Integer> clienteRepresentante;

    @Inject
    public GrupoclienteEditForm(GrupoclienteRepository grupoclienteRepository, GrupoclienteGraphLoader grupoclienteGraphLoader) {
        super(grupoclienteRepository, grupoclienteGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public Grupocliente getGrupocliente() {
        return getEntity();
    }

    @PostConstruct
    void setupClienteRepresentantesActions() {
        clienteRepresentante = new GenericToOneAssociation<Cliente, Integer>("grupocliente_clienteRepresentante", clienteController) {
            @Override
            protected Cliente get() {
                return getGrupocliente().getClienteRepresentante();
            }

            @Override
            protected void set(Cliente cliente) {
                getGrupocliente().setClienteRepresentante(cliente);
            }

            @NotNull
            @Override
            public Cliente getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Cliente, Integer> getClienteRepresentante() {
        return clienteRepresentante;
    }
}
