/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.domain.ItensOs;
import br.com.aj2.repository.ItensOsRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.ItensOsPermission;

/**
 * Stateless controller for {@link ItensOs} conversation start. 
 */
@Named
@Singleton
public class ItensOsController extends GenericController<ItensOs, Integer> {
    private static final String editUri = "/domain/itensOsEdit.faces";
    private static final String selectUri = "/domain/itensOsSelect.faces";

    @Inject
    public ItensOsController(ItensOsRepository itensOsRepository, ItensOsPermission itensOsPermission) {
        super(itensOsRepository, itensOsPermission, selectUri, editUri);
    }

}