/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;
import br.com.aj2.domain.ItensOs;
import br.com.aj2.domain.Os;
import br.com.aj2.domain.Servicos;
import br.com.aj2.repository.ItensOsRepository;
import br.com.aj2.web.domain.ItensOsGraphLoader;
import br.com.aj2.web.domain.OsController;
import br.com.aj2.web.domain.ServicosController;
import br.com.aj2.web.domain.support.GenericEditForm;
import br.com.aj2.web.domain.support.GenericToOneAssociation;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link ItensOs}.
 */
@Named
@ConversationContextScoped
public class ItensOsEditForm extends GenericEditForm<ItensOs, Integer> {
    @Inject
    protected ServicosController servicosController;
    protected GenericToOneAssociation<Servicos, Integer> servicos;
    @Inject
    protected OsController osController;
    protected GenericToOneAssociation<Os, Integer> itensOss;

    @Inject
    public ItensOsEditForm(ItensOsRepository itensOsRepository, ItensOsGraphLoader itensOsGraphLoader) {
        super(itensOsRepository, itensOsGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public ItensOs getItensOs() {
        return getEntity();
    }

 
    @PostConstruct
    void setupServicossActions() {
        if (getEntity().getServicos() == null){
            getEntity().setAdicionais(0.0);
            getEntity().setDesconto(0.0);
            getEntity().setQuantidade(1);
            getEntity().setValor(0.0);        
        }
        servicos = new GenericToOneAssociation<Servicos, Integer>("itensOs_servicos", servicosController) {
            @Override
            protected Servicos get() {
                return getItensOs().getServicos();
            }

            @Override
            protected void set(Servicos servicos) {
                getItensOs().setServicos(servicos);
                getItensOs().setValor(servicos.getValor());
            }

            @NotNull
            @Override
            public Servicos getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Servicos, Integer> getServicos() {
        return servicos;
    }

    @PostConstruct
    void setupItensOssesActions() {
        itensOss = new GenericToOneAssociation<Os, Integer>("itensOs_itensOss", osController) {
            @Override
            protected Os get() {
                return getItensOs().getOs();
            }

            @Override
            protected void set(Os os) {
                getItensOs().setOs(os);
            }

            @NotNull
            @Override
            public Os getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Os, Integer> getOs() {
        return itensOss;
    }
}
