/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import br.com.aj2.domain.Lancamentos;
import br.com.aj2.repository.LancamentosRepository;
import br.com.aj2.web.converter.LancamentosJsfConverter;
import br.com.aj2.web.domain.support.GenericLazyDataModel;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Lancamentos}
 */
@Named
@ConversationContextScoped
public class LancamentosLazyDataModel extends GenericLazyDataModel<Lancamentos, Integer, LancamentosSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public LancamentosLazyDataModel(LancamentosRepository lancamentosRepository, LancamentosJsfConverter lancamentosConverter,
            LancamentosController lancamentosController, LancamentosSearchForm lancamentosSearchForm) {
        super(lancamentosRepository, lancamentosConverter, lancamentosController, lancamentosSearchForm);
    }
}