/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Produtor;
import br.com.aj2.domain.Produtor_;
import br.com.aj2.repository.ProdutorRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.ProdutorPermission;

/**
 * Stateless controller for {@link Produtor} conversation start. 
 */
@Named
@Singleton
public class ProdutorController extends GenericController<Produtor, Integer> {
    private static final String editUri = "/domain/produtorEdit.faces";
    private static final String selectUri = "/domain/produtorSelect.faces";

    @Inject
    public ProdutorController(ProdutorRepository produtorRepository, ProdutorPermission produtorPermission) {
        super(produtorRepository, produtorPermission, selectUri, editUri);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        searchParameters.orderBy(Produtor_.cpfCnpj);
        return searchParameters;
    }

}