/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package br.com.aj2.web.domain;

import static br.com.aj2.dao.support.PropertySelector.newPropertySelector;
import static br.com.aj2.dao.support.Ranges.RangeDate.newRangeDate;
import static br.com.aj2.dao.support.Ranges.RangeDouble.newRangeDouble;
import javax.inject.Named;
import br.com.aj2.dao.support.PropertySelector;
import br.com.aj2.dao.support.Ranges.RangeDate;
import br.com.aj2.dao.support.Ranges.RangeDouble;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Produtor;
import br.com.aj2.domain.Produtor_;
import br.com.aj2.enumTypes.EstadoCivil;
import br.com.aj2.enumTypes.Sexo;
import br.com.aj2.enumTypes.TipoPessoa;
import br.com.aj2.enumTypes.UF;
import br.com.aj2.web.domain.support.GenericSearchForm;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Produtor}.
 * It exposes a {@link Produtor} instance so it can be used in search by Example query.
 */
@Named
@ConversationContextScoped
public class ProdutorSearchForm extends GenericSearchForm<Produtor, Integer, ProdutorSearchForm> {
    private static final long serialVersionUID = 1L;

    protected Produtor produtor = new Produtor();
    protected RangeDate<Produtor> dataNascimentoRange = newRangeDate(Produtor_.dataNascimento);
    protected RangeDouble<Produtor> valorComissaoRange = newRangeDouble(Produtor_.valorComissao);
    protected RangeDouble<Produtor> salarioRange = newRangeDouble(Produtor_.salario);
    protected PropertySelector<Produtor, String> nomeSelector = newPropertySelector(Produtor_.nome);
    protected PropertySelector<Produtor, Sexo> sexoSelector = newPropertySelector(Produtor_.sexo);
    protected PropertySelector<Produtor, EstadoCivil> estadoCivilSelector = newPropertySelector(Produtor_.estadoCivil);
    protected PropertySelector<Produtor, String> cpfCnpjSelector = newPropertySelector(Produtor_.cpfCnpj);
    protected PropertySelector<Produtor, String> rgIeSelector = newPropertySelector(Produtor_.rgIe);
    protected PropertySelector<Produtor, TipoPessoa> tipoPessoaSelector = newPropertySelector(Produtor_.tipoPessoa);
    protected PropertySelector<Produtor, String> logradouroSelector = newPropertySelector(Produtor_.logradouro);
    protected PropertySelector<Produtor, String> complementoSelector = newPropertySelector(Produtor_.complemento);
    protected PropertySelector<Produtor, String> bairroSelector = newPropertySelector(Produtor_.bairro);
    protected PropertySelector<Produtor, String> cidadeSelector = newPropertySelector(Produtor_.cidade);
    protected PropertySelector<Produtor, UF> ufSelector = newPropertySelector(Produtor_.uf);
    protected PropertySelector<Produtor, String> paisSelector = newPropertySelector(Produtor_.pais);
    protected PropertySelector<Produtor, String> cepSelector = newPropertySelector(Produtor_.cep);
    protected PropertySelector<Produtor, String> telefoneSelector = newPropertySelector(Produtor_.telefone);
    protected PropertySelector<Produtor, String> faxSelector = newPropertySelector(Produtor_.fax);
    protected PropertySelector<Produtor, String> celularSelector = newPropertySelector(Produtor_.celular);
    protected PropertySelector<Produtor, String> emailSelector = newPropertySelector(Produtor_.email);
    protected PropertySelector<Produtor, String> facebookSelector = newPropertySelector(Produtor_.facebook);
    protected PropertySelector<Produtor, String> skypeSelector = newPropertySelector(Produtor_.skype);
    protected PropertySelector<Produtor, String> msnSelector = newPropertySelector(Produtor_.msn);
    protected PropertySelector<Produtor, String> siteSelector = newPropertySelector(Produtor_.site);
    protected PropertySelector<Produtor, Double> valorComissaoSelector = newPropertySelector(Produtor_.valorComissao);
    protected PropertySelector<Produtor, Double> salarioSelector = newPropertySelector(Produtor_.salario);
    protected PropertySelector<Produtor, String> descriptionSelector = newPropertySelector(Produtor_.description);

    public Produtor getProdutor() {
        return produtor;
    }

    @Override
    protected Produtor getEntity() {
        return getProdutor();
    }

    @Override
    public ProdutorSearchForm newInstance() {
        return new ProdutorSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        return new SearchParameters() //
                .anywhere() //
                .range(dataNascimentoRange) //
                .range(valorComissaoRange) //
                .range(salarioRange) //
                .property(nomeSelector) //
                .property(sexoSelector) //
                .property(estadoCivilSelector) //
                .property(cpfCnpjSelector) //
                .property(rgIeSelector) //
                .property(tipoPessoaSelector) //
                .property(logradouroSelector) //
                .property(complementoSelector) //
                .property(bairroSelector) //
                .property(cidadeSelector) //
                .property(ufSelector) //
                .property(paisSelector) //
                .property(cepSelector) //
                .property(telefoneSelector) //
                .property(faxSelector) //
                .property(celularSelector) //
                .property(emailSelector) //
                .property(facebookSelector) //
                .property(skypeSelector) //
                .property(msnSelector) //
                .property(siteSelector) //
                .property(valorComissaoSelector) //
                .property(salarioSelector) //
                .property(descriptionSelector) //
        ;
    }

    @Override
    public void resetWithOther(ProdutorSearchForm other) {
        this.produtor = other.getProdutor();
        this.dataNascimentoRange = other.getDataNascimentoRange();
        this.valorComissaoRange = other.getValorComissaoRange();
        this.salarioRange = other.getSalarioRange();
        this.nomeSelector = other.getNomeSelector();
        this.sexoSelector = other.getSexoSelector();
        this.estadoCivilSelector = other.getEstadoCivilSelector();
        this.cpfCnpjSelector = other.getCpfCnpjSelector();
        this.rgIeSelector = other.getRgIeSelector();
        this.tipoPessoaSelector = other.getTipoPessoaSelector();
        this.logradouroSelector = other.getLogradouroSelector();
        this.complementoSelector = other.getComplementoSelector();
        this.bairroSelector = other.getBairroSelector();
        this.cidadeSelector = other.getCidadeSelector();
        this.ufSelector = other.getUfSelector();
        this.paisSelector = other.getPaisSelector();
        this.cepSelector = other.getCepSelector();
        this.telefoneSelector = other.getTelefoneSelector();
        this.faxSelector = other.getFaxSelector();
        this.celularSelector = other.getCelularSelector();
        this.emailSelector = other.getEmailSelector();
        this.facebookSelector = other.getFacebookSelector();
        this.skypeSelector = other.getSkypeSelector();
        this.msnSelector = other.getMsnSelector();
        this.siteSelector = other.getSiteSelector();
        this.valorComissaoSelector = other.getValorComissaoSelector();
        this.salarioSelector = other.getSalarioSelector();
        this.descriptionSelector = other.getDescriptionSelector();
    }

    // Ranges
    public RangeDate<Produtor> getDataNascimentoRange() {
        return dataNascimentoRange;
    }

    public RangeDouble<Produtor> getValorComissaoRange() {
        return valorComissaoRange;
    }

    public RangeDouble<Produtor> getSalarioRange() {
        return salarioRange;
    }

    // Property selectors
    public PropertySelector<Produtor, String> getNomeSelector() {
        return nomeSelector;
    }

    public PropertySelector<Produtor, Sexo> getSexoSelector() {
        return sexoSelector;
    }

    public PropertySelector<Produtor, EstadoCivil> getEstadoCivilSelector() {
        return estadoCivilSelector;
    }

    public PropertySelector<Produtor, String> getCpfCnpjSelector() {
        return cpfCnpjSelector;
    }

    public PropertySelector<Produtor, String> getRgIeSelector() {
        return rgIeSelector;
    }

    public PropertySelector<Produtor, TipoPessoa> getTipoPessoaSelector() {
        return tipoPessoaSelector;
    }

    public PropertySelector<Produtor, String> getLogradouroSelector() {
        return logradouroSelector;
    }

    public PropertySelector<Produtor, String> getComplementoSelector() {
        return complementoSelector;
    }

    public PropertySelector<Produtor, String> getBairroSelector() {
        return bairroSelector;
    }

    public PropertySelector<Produtor, String> getCidadeSelector() {
        return cidadeSelector;
    }

    public PropertySelector<Produtor, UF> getUfSelector() {
        return ufSelector;
    }

    public PropertySelector<Produtor, String> getPaisSelector() {
        return paisSelector;
    }

    public PropertySelector<Produtor, String> getCepSelector() {
        return cepSelector;
    }

    public PropertySelector<Produtor, String> getTelefoneSelector() {
        return telefoneSelector;
    }

    public PropertySelector<Produtor, String> getFaxSelector() {
        return faxSelector;
    }

    public PropertySelector<Produtor, String> getCelularSelector() {
        return celularSelector;
    }

    public PropertySelector<Produtor, String> getEmailSelector() {
        return emailSelector;
    }

    public PropertySelector<Produtor, String> getFacebookSelector() {
        return facebookSelector;
    }

    public PropertySelector<Produtor, String> getSkypeSelector() {
        return skypeSelector;
    }

    public PropertySelector<Produtor, String> getMsnSelector() {
        return msnSelector;
    }

    public PropertySelector<Produtor, String> getSiteSelector() {
        return siteSelector;
    }

    public PropertySelector<Produtor, Double> getValorComissaoSelector() {
        return valorComissaoSelector;
    }

    public PropertySelector<Produtor, Double> getSalarioSelector() {
        return salarioSelector;
    }

    public PropertySelector<Produtor, String> getDescriptionSelector() {
        return descriptionSelector;
    }
}
