/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import br.com.aj2.domain.Servicos;
import br.com.aj2.repository.ServicosRepository;
import br.com.aj2.web.converter.ServicosJsfConverter;
import br.com.aj2.web.domain.support.GenericLazyDataModel;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Servicos}
 */
@Named
@ConversationContextScoped
public class ServicosLazyDataModel extends GenericLazyDataModel<Servicos, Integer, ServicosSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public ServicosLazyDataModel(ServicosRepository servicosRepository, ServicosJsfConverter servicosConverter, ServicosController servicosController,
            ServicosSearchForm servicosSearchForm) {
        super(servicosRepository, servicosConverter, servicosController, servicosSearchForm);
    }
}