/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.TipoEquipamento;
import br.com.aj2.domain.TipoEquipamento_;
import br.com.aj2.repository.TipoEquipamentoRepository;
import br.com.aj2.web.converter.TipoEquipamentoJsfConverter;
import br.com.aj2.web.domain.support.GenericLazyDataModel;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link TipoEquipamento}
 */
@Named
@ConversationContextScoped
public class TipoEquipamentoLazyDataModel extends GenericLazyDataModel<TipoEquipamento, Integer, TipoEquipamentoSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public TipoEquipamentoLazyDataModel(TipoEquipamentoRepository tipoEquipamentoRepository, TipoEquipamentoJsfConverter tipoEquipamentoConverter,
            TipoEquipamentoController tipoEquipamentoController, TipoEquipamentoSearchForm tipoEquipamentoSearchForm) {
        super(tipoEquipamentoRepository, tipoEquipamentoConverter, tipoEquipamentoController, tipoEquipamentoSearchForm);
    }

    @Override
    protected void defaultOrder(SearchParameters sp) {
        sp.orderBy(TipoEquipamento_.descricao);
    }
}