/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.TipoEquipamento;
import br.com.aj2.domain.TipoEquipamento_;
import br.com.aj2.repository.TipoEquipamentoRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.TipoEquipamentoPermission;

/**
 * Stateless controller for {@link TipoEquipamento} conversation start. 
 */
@Named
@Singleton
public class TipoEquipamentoController extends GenericController<TipoEquipamento, Integer> {
    private static final String editUri = "/domain/tipoEquipamentoEdit.faces";
    private static final String selectUri = "/domain/tipoEquipamentoSelect.faces";

    @Inject
    public TipoEquipamentoController(TipoEquipamentoRepository tipoEquipamentoRepository, TipoEquipamentoPermission tipoEquipamentoPermission) {
        super(tipoEquipamentoRepository, tipoEquipamentoPermission, selectUri, editUri);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        searchParameters.orderBy(TipoEquipamento_.descricao);
        return searchParameters;
    }

}