/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/selectitem.enum.vm.java
 */
package br.com.aj2.enumTypes;

import static com.google.common.collect.Lists.newArrayList;

import java.util.List;

import javax.inject.Named;
import javax.inject.Singleton;
import javax.faces.model.SelectItem;

import br.com.aj2.enumTypes.UF;

/**
 * Helper to support the h:selectOneRadio and h:selectOneMenu for UF.
 */
@Named
@Singleton
public class UFItems {

    /**
     * Returns a list of SelectItem/UF ready to use in a h:selectOneRadio, h:selectOneMenu or p:selectManyCheckbox tags
     */
    public List<SelectItem> getList() {
        List<SelectItem> result = newArrayList();
        for (UF uF : UF.values()) {
            result.add(new SelectItem(uF, uF.getLabel()));
        }

        return result;
    }
}
