/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package br.com.aj2.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Agenda.class)
public abstract class Agenda_ {

    // Raw attributes
    public static volatile SingularAttribute<Agenda, Integer> id;
    public static volatile SingularAttribute<Agenda, String> evento;
    public static volatile SingularAttribute<Agenda, Date> data;
    public static volatile SingularAttribute<Agenda, String> hora;
    public static volatile SingularAttribute<Agenda, String> arquivoFileName;
    public static volatile SingularAttribute<Agenda, String> descricao;
    public static volatile SingularAttribute<Agenda, byte[]> arquivoBinary;
    public static volatile SingularAttribute<Agenda, String> arquivoContentType;
}