/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package br.com.aj2.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import br.com.aj2.domain.Grupocliente;
import br.com.aj2.enumTypes.EstadoCivil;
import br.com.aj2.enumTypes.Sexo;
import br.com.aj2.enumTypes.TipoPessoa;
import br.com.aj2.enumTypes.UF;

@StaticMetamodel(Cliente.class)
public abstract class Cliente_ {

    // Raw attributes
    public static volatile SingularAttribute<Cliente, Integer> id;
    public static volatile SingularAttribute<Cliente, String> nome;
    public static volatile SingularAttribute<Cliente, Sexo> sexo;
    public static volatile SingularAttribute<Cliente, Date> dataNascimento;
    public static volatile SingularAttribute<Cliente, EstadoCivil> estadoCivil;
    public static volatile SingularAttribute<Cliente, String> cpfCnpj;
    public static volatile SingularAttribute<Cliente, String> rgIe;
    public static volatile SingularAttribute<Cliente, TipoPessoa> tipoPessoa;
    public static volatile SingularAttribute<Cliente, String> logradouro;
    public static volatile SingularAttribute<Cliente, String> numero;
    public static volatile SingularAttribute<Cliente, String> complemento;
    public static volatile SingularAttribute<Cliente, String> bairro;
    public static volatile SingularAttribute<Cliente, String> cidade;
    public static volatile SingularAttribute<Cliente, UF> uf;
    public static volatile SingularAttribute<Cliente, String> pais;
    public static volatile SingularAttribute<Cliente, String> cep;
    public static volatile SingularAttribute<Cliente, String> telefone;
    public static volatile SingularAttribute<Cliente, String> fax;
    public static volatile SingularAttribute<Cliente, String> celular;
    public static volatile SingularAttribute<Cliente, String> email;
    public static volatile SingularAttribute<Cliente, String> facebook;
    public static volatile SingularAttribute<Cliente, String> skype;
    public static volatile SingularAttribute<Cliente, String> msn;
    public static volatile SingularAttribute<Cliente, String> site;
    public static volatile SingularAttribute<Cliente, Date> creationDate;
    public static volatile SingularAttribute<Cliente, String> lastModificationAuthor;
    public static volatile SingularAttribute<Cliente, Date> lastModificationDate;
    public static volatile SingularAttribute<Cliente, String> creationAuthor;
    public static volatile SingularAttribute<Cliente, String> description;

    // Many to one
    public static volatile SingularAttribute<Cliente, Grupocliente> grupoCliente;
}