/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package br.com.aj2.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import br.com.aj2.domain.IdentifiableHashBuilder;
import br.com.aj2.domain.ItensOs_;
import br.com.aj2.domain.Os;
import br.com.aj2.domain.Servicos;
import com.google.common.base.Objects;

@Entity
@Table(name = "itens_os")
public class ItensOs implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(ItensOs.class);

    // Raw attributes
    private Integer id; // pk
    private Double valor;
    private Double desconto;
    private Integer quantidade;
    private Double adicionais;
    private Double total;

    // Many to one
    private Servicos servicos; // not null (servicosId)
    private Os os; // not null (osId)

    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public ItensOs id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [valor] ------------------------

    @Column(name = "valor", precision = 22)
    public Double getValor() {
        return valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public ItensOs valor(Double valor) {
        setValor(valor);
        return this;
    }

    // -- [desconto] ------------------------

    @Column(name = "desconto", precision = 22)
    public Double getDesconto() {
        return desconto;
    }

    public void setDesconto(Double desconto) {
        this.desconto = desconto;
    }

    public ItensOs desconto(Double desconto) {
        setDesconto(desconto);
        return this;
    }

    // -- [quantidade] ------------------------

    @Column(name = "quantidade", precision = 10)
    public Integer getQuantidade() {
        return quantidade;
    }

    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }

    public ItensOs quantidade(Integer quantidade) {
        setQuantidade(quantidade);
        return this;
    }

    // -- [adicionais] ------------------------

    @Column(name = "adicionais", precision = 22)
    public Double getAdicionais() {
        return adicionais;
    }

    public void setAdicionais(Double adicionais) {
        this.adicionais = adicionais;
    }

    public ItensOs adicionais(Double adicionais) {
        setAdicionais(adicionais);
        return this;
    }

    // -- [total] ------------------------

    @Transient
    public Double getTotal() {
        if (getValor() != null){
            if (getDesconto() != 0.0 ){
                total = (getValor()*getQuantidade())+getAdicionais();
                total = total - ((total*getDesconto())/100);
            }else{
                total = (getValor()*getQuantidade())+getAdicionais();
            }
           setTotal(total);
        }
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public ItensOs total(Double total) {
        setTotal(total);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: ItensOs.servicosId ==> Servicos.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "servicos_id", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE })
    public Servicos getServicos() {
        return servicos;
    }

    /**
     * Set the {@link #servicos} without adding this ItensOs instance on the passed {@link #servicos}
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link Servicos}
     */
    public void setServicos(Servicos servicos) {
        this.servicos = servicos;
    }

    public ItensOs servicos(Servicos servicos) {
        setServicos(servicos);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: ItensOs.osId ==> Os.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "os_id", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE })
    public Os getOs() {
        return os;
    }

    /**
     * Set the {@link #itensOss} without adding this ItensOs instance on the passed {@link #itensOss}
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link Os}
     */
    public void setOs(Os os) {
        this.os = os;
    }

    public ItensOs oS(Os os) {
        setOs(os);
        return this;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ItensOs && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this ItensOs instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(ItensOs_.id.getName(), getId()) //
                .add(ItensOs_.valor.getName(), getValor()) //
                .add(ItensOs_.desconto.getName(), getDesconto()) //
                .add(ItensOs_.quantidade.getName(), getQuantidade()) //
                .add(ItensOs_.adicionais.getName(), getAdicionais()) //
                .add(ItensOs_.total.getName(), getTotal()) //
                .toString();
    }
}