/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package br.com.aj2.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import br.com.aj2.domain.Os;
import br.com.aj2.domain.Servicos;

@StaticMetamodel(ItensOs.class)
public abstract class ItensOs_ {

    // Raw attributes
    public static volatile SingularAttribute<ItensOs, Integer> id;
    public static volatile SingularAttribute<ItensOs, Double> valor;
    public static volatile SingularAttribute<ItensOs, Double> desconto;
    public static volatile SingularAttribute<ItensOs, Integer> quantidade;
    public static volatile SingularAttribute<ItensOs, Double> adicionais;
    public static volatile SingularAttribute<ItensOs, Double> total;

    // Many to one
    public static volatile SingularAttribute<ItensOs, Servicos> servicos;
    public static volatile SingularAttribute<ItensOs, Os> Os;
    public static volatile SingularAttribute<ItensOs, Os> os;
}