/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package br.com.aj2.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import br.com.aj2.domain.Cliente;
import br.com.aj2.domain.Estudios;
import br.com.aj2.enumTypes.FormaPagamento;
import br.com.aj2.enumTypes.StatusLocacao;

@StaticMetamodel(Locacao.class)
public abstract class Locacao_ {

    // Raw attributes
    public static volatile SingularAttribute<Locacao, Integer> id;
    public static volatile SingularAttribute<Locacao, Date> data;
    public static volatile SingularAttribute<Locacao, String> hora;
    public static volatile SingularAttribute<Locacao, String> qtdHoras;
    public static volatile SingularAttribute<Locacao, Double> valor;
    public static volatile SingularAttribute<Locacao, Boolean> pago;
    public static volatile SingularAttribute<Locacao, FormaPagamento> formaPagamento;
    public static volatile SingularAttribute<Locacao, String> obsduranteouso;
    public static volatile SingularAttribute<Locacao, Date> creationDate;
    public static volatile SingularAttribute<Locacao, String> lastModificationAuthor;
    public static volatile SingularAttribute<Locacao, Date> lastModificationDate;
    public static volatile SingularAttribute<Locacao, String> creationAuthor;
    public static volatile SingularAttribute<Locacao, StatusLocacao> status;
    public static volatile SingularAttribute<Locacao, String> description;

    // Many to one
    public static volatile SingularAttribute<Locacao, Estudios> estudios;
    public static volatile SingularAttribute<Locacao, Cliente> cliente;
}