/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package br.com.aj2.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.EnumType.STRING;
import static javax.persistence.TemporalType.DATE;
import static javax.persistence.TemporalType.TIMESTAMP;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import br.com.aj2.audit.AuditContextHolder;
import br.com.aj2.domain.Cliente;
import br.com.aj2.domain.Estudios;
import br.com.aj2.domain.IdentifiableHashBuilder;
import br.com.aj2.domain.Locacao_;
import br.com.aj2.enumTypes.FormaPagamento;
import br.com.aj2.enumTypes.StatusLocacao;
import com.google.common.base.Objects;

@Entity
@Table(name = "locacao")
public class Locacao implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Locacao.class);

    // Raw attributes
    private Integer id; // pk
    private Date data;
    private String hora;
    private String qtdHoras;
    private Double valor;
    private Boolean pago;
    private FormaPagamento formaPagamento;
    private String obsduranteouso;
    private Date creationDate;
    private String lastModificationAuthor;
    private Date lastModificationDate;
    private String creationAuthor;
    private StatusLocacao status;
    private String description;

    // Many to one
    private Estudios estudios; // not null (estudiosId)
    private Cliente cliente; // not null (clienteId)

    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Locacao id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [data] ------------------------

    @Column(name = "`data`", length = 10)
    @Temporal(DATE)
    public Date getData() {
        return data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    public Locacao data(Date data) {
        setData(data);
        return this;
    }

    // -- [hora] ------------------------

    @Size(max = 45)
    @Column(name = "hora", length = 45)
    public String getHora() {
        return hora;
    }

    public void setHora(String hora) {
        this.hora = hora;
    }

    public Locacao hora(String hora) {
        setHora(hora);
        return this;
    }

    // -- [qtdHoras] ------------------------

    @Size(max = 45)
    @Column(name = "qtd_horas", length = 45)
    public String getQtdHoras() {
        return qtdHoras;
    }

    public void setQtdHoras(String qtdHoras) {
        this.qtdHoras = qtdHoras;
    }

    public Locacao qtdHoras(String qtdHoras) {
        setQtdHoras(qtdHoras);
        return this;
    }

    // -- [valor] ------------------------

    @Column(name = "valor", precision = 22)
    public Double getValor() {
        return valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public Locacao valor(Double valor) {
        setValor(valor);
        return this;
    }

    // -- [pago] ------------------------

    @Column(name = "pago", length = 0)
    public Boolean getPago() {
        return pago;
    }

    public void setPago(Boolean pago) {
        this.pago = pago;
    }

    public Locacao pago(Boolean pago) {
        setPago(pago);
        return this;
    }

    // -- [formaPagamento] ------------------------

    @Column(name = "forma_pagamento", length = 45)
    @Enumerated(STRING)
    public FormaPagamento getFormaPagamento() {
        return formaPagamento;
    }

    public void setFormaPagamento(FormaPagamento formaPagamento) {
        this.formaPagamento = formaPagamento;
    }

    public Locacao formaPagamento(FormaPagamento formaPagamento) {
        setFormaPagamento(formaPagamento);
        return this;
    }

    // -- [obsduranteouso] ------------------------

    @Size(max = 65535)
    @Column(name = "obsduranteouso", length = 65535)
    public String getObsduranteouso() {
        return obsduranteouso;
    }

    public void setObsduranteouso(String obsduranteouso) {
        this.obsduranteouso = obsduranteouso;
    }

    public Locacao obsduranteouso(String obsduranteouso) {
        setObsduranteouso(obsduranteouso);
        return this;
    }

    // -- [creationDate] ------------------------

    @Column(name = "creation_date", length = 19)
    @Temporal(TIMESTAMP)
    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Locacao creationDate(Date creationDate) {
        setCreationDate(creationDate);
        return this;
    }

    // -- [lastModificationAuthor] ------------------------

    @Column(name = "last_modification_author", length = 200)
    public String getLastModificationAuthor() {
        return lastModificationAuthor;
    }

    public void setLastModificationAuthor(String lastModificationAuthor) {
        this.lastModificationAuthor = lastModificationAuthor;
    }

    public Locacao lastModificationAuthor(String lastModificationAuthor) {
        setLastModificationAuthor(lastModificationAuthor);
        return this;
    }

    // -- [lastModificationDate] ------------------------

    @Column(name = "last_modification_date", length = 19)
    @Temporal(TIMESTAMP)
    public Date getLastModificationDate() {
        return lastModificationDate;
    }

    public void setLastModificationDate(Date lastModificationDate) {
        this.lastModificationDate = lastModificationDate;
    }

    public Locacao lastModificationDate(Date lastModificationDate) {
        setLastModificationDate(lastModificationDate);
        return this;
    }

    // -- [creationAuthor] ------------------------

    @Column(name = "creation_author", length = 200)
    public String getCreationAuthor() {
        return creationAuthor;
    }

    public void setCreationAuthor(String creationAuthor) {
        this.creationAuthor = creationAuthor;
    }

    public Locacao creationAuthor(String creationAuthor) {
        setCreationAuthor(creationAuthor);
        return this;
    }

    // -- [status] ------------------------

    @Column(name = "status", length = 45)
    @Enumerated(STRING)
    public StatusLocacao getStatus() {
        return status;
    }

    public void setStatus(StatusLocacao status) {
        this.status = status;
    }

    public Locacao status(StatusLocacao status) {
        setStatus(status);
        return this;
    }

    // -- [description] ------------------------

    @Size(max = 45)
    @Column(name = "description", length = 45)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Locacao description(String description) {
        setDescription(description);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Locacao.estudiosId ==> Estudios.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "estudios_id", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE })
    public Estudios getEstudios() {
        return estudios;
    }

    /**
     * Set the {@link #estudios} without adding this Locacao instance on the passed {@link #estudios}
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link Estudios}
     */
    public void setEstudios(Estudios estudios) {
        this.estudios = estudios;
    }

    public Locacao estudios(Estudios estudios) {
        setEstudios(estudios);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Locacao.clienteId ==> Cliente.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "cliente_id", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE })
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * Set the {@link #cliente} without adding this Locacao instance on the passed {@link #cliente}
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link Cliente}
     */
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Locacao cliente(Cliente cliente) {
        setCliente(cliente);
        return this;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Locacao && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Locacao instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Locacao_.id.getName(), getId()) //
                .add(Locacao_.data.getName(), getData()) //
                .add(Locacao_.hora.getName(), getHora()) //
                .add(Locacao_.qtdHoras.getName(), getQtdHoras()) //
                .add(Locacao_.valor.getName(), getValor()) //
                .add(Locacao_.pago.getName(), getPago()) //
                .add(Locacao_.formaPagamento.getName(), getFormaPagamento()) //
                .add(Locacao_.obsduranteouso.getName(), getObsduranteouso()) //
                .add(Locacao_.creationDate.getName(), getCreationDate()) //
                .add(Locacao_.lastModificationAuthor.getName(), getLastModificationAuthor()) //
                .add(Locacao_.lastModificationDate.getName(), getLastModificationDate()) //
                .add(Locacao_.creationAuthor.getName(), getCreationAuthor()) //
                .add(Locacao_.status.getName(), getStatus()) //
                .add(Locacao_.description.getName(), getDescription()) //
                .toString();
    }

    @PrePersist
    protected void prePersist() {
        if (AuditContextHolder.audit()) {
            setCreationAuthor(AuditContextHolder.username());
            setCreationDate(new Date());
        }
    }

    @PreUpdate
    protected void preUpdate() {
        if (AuditContextHolder.audit()) {
            setLastModificationAuthor(AuditContextHolder.username());
            setLastModificationDate(new Date());
        }
    }
}