/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package br.com.aj2.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import br.com.aj2.enumTypes.EstadoCivil;
import br.com.aj2.enumTypes.Sexo;
import br.com.aj2.enumTypes.TipoPessoa;
import br.com.aj2.enumTypes.UF;

@StaticMetamodel(Produtor.class)
public abstract class Produtor_ {

    // Raw attributes
    public static volatile SingularAttribute<Produtor, Integer> id;
    public static volatile SingularAttribute<Produtor, String> nome;
    public static volatile SingularAttribute<Produtor, Sexo> sexo;
    public static volatile SingularAttribute<Produtor, Date> dataNascimento;
    public static volatile SingularAttribute<Produtor, EstadoCivil> estadoCivil;
    public static volatile SingularAttribute<Produtor, String> cpfCnpj;
    public static volatile SingularAttribute<Produtor, String> rgIe;
    public static volatile SingularAttribute<Produtor, TipoPessoa> tipoPessoa;
    public static volatile SingularAttribute<Produtor, String> logradouro;
    public static volatile SingularAttribute<Produtor, String> complemento;
    public static volatile SingularAttribute<Produtor, String> bairro;
    public static volatile SingularAttribute<Produtor, String> cidade;
    public static volatile SingularAttribute<Produtor, UF> uf;
    public static volatile SingularAttribute<Produtor, String> pais;
    public static volatile SingularAttribute<Produtor, String> cep;
    public static volatile SingularAttribute<Produtor, String> telefone;
    public static volatile SingularAttribute<Produtor, String> fax;
    public static volatile SingularAttribute<Produtor, String> celular;
    public static volatile SingularAttribute<Produtor, String> email;
    public static volatile SingularAttribute<Produtor, String> facebook;
    public static volatile SingularAttribute<Produtor, String> skype;
    public static volatile SingularAttribute<Produtor, String> msn;
    public static volatile SingularAttribute<Produtor, String> site;
    public static volatile SingularAttribute<Produtor, Double> valorComissao;
    public static volatile SingularAttribute<Produtor, Double> salario;
    public static volatile SingularAttribute<Produtor, Date> creationDate;
    public static volatile SingularAttribute<Produtor, String> lastModificationAuthor;
    public static volatile SingularAttribute<Produtor, Date> lastModificationDate;
    public static volatile SingularAttribute<Produtor, String> creationAuthor;
    public static volatile SingularAttribute<Produtor, String> description;
}