/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package br.com.aj2.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(TipoEquipamento.class)
public abstract class TipoEquipamento_ {

    // Raw attributes
    public static volatile SingularAttribute<TipoEquipamento, Integer> id;
    public static volatile SingularAttribute<TipoEquipamento, String> descricao;
}