/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package br.com.aj2.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import br.com.aj2.enumTypes.TipoPessoa;
import br.com.aj2.enumTypes.UF;

@StaticMetamodel(Empresa.class)
public abstract class Empresa_ {

    // Raw attributes
    public static volatile SingularAttribute<Empresa, Integer> id;
    public static volatile SingularAttribute<Empresa, String> razaosocial;
    public static volatile SingularAttribute<Empresa, String> cnpj;
    public static volatile SingularAttribute<Empresa, String> ie;
    public static volatile SingularAttribute<Empresa, String> nomeFantasia;
    public static volatile SingularAttribute<Empresa, String> sigla;
    public static volatile SingularAttribute<Empresa, String> telefone;
    public static volatile SingularAttribute<Empresa, String> fax;
    public static volatile SingularAttribute<Empresa, String> facebook;
    public static volatile SingularAttribute<Empresa, String> site;
    public static volatile SingularAttribute<Empresa, String> email;
    public static volatile SingularAttribute<Empresa, String> logradouro;
    public static volatile SingularAttribute<Empresa, String> complemento;
    public static volatile SingularAttribute<Empresa, String> numero;
    public static volatile SingularAttribute<Empresa, String> bairro;
    public static volatile SingularAttribute<Empresa, String> cidade;
    public static volatile SingularAttribute<Empresa, UF> uf;
    public static volatile SingularAttribute<Empresa, String> cep;
    public static volatile SingularAttribute<Empresa, Date> expiredate;
    public static volatile SingularAttribute<Empresa, String> serialhd;
    public static volatile SingularAttribute<Empresa, Boolean> ativo;
    public static volatile SingularAttribute<Empresa, String> plano;
    public static volatile SingularAttribute<Empresa, String> logo;
    public static volatile SingularAttribute<Empresa, TipoPessoa> tipoPessoa;
    public static volatile SingularAttribute<Empresa, String> botonrelatorio;
    public static volatile SingularAttribute<Empresa, byte[]> logomarcaBinary;
    public static volatile SingularAttribute<Empresa, String> logomarcaFileName;
    public static volatile SingularAttribute<Empresa, String> logomarcaContentType;
    public static volatile SingularAttribute<Empresa, String> hostname;
    public static volatile SingularAttribute<Empresa, String> ssl;
    public static volatile SingularAttribute<Empresa, String> tls;
    public static volatile SingularAttribute<Empresa, String> password;
    public static volatile SingularAttribute<Empresa, String> emailOrigem;
    public static volatile SingularAttribute<Empresa, String> username;
    public static volatile SingularAttribute<Empresa, Integer> port;
}