/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package br.com.aj2.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.TemporalType.DATE;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;
import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import br.com.aj2.domain.Equipamentos_;
import br.com.aj2.domain.TipoEquipamento;
import com.google.common.base.Objects;

@Entity
@Table(name = "equipamentos")
public class Equipamentos implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Equipamentos.class);

    // Raw attributes
    private Integer id; // pk
    private String descricao; // unique (not null)
    private Double valor;
    private Date dataAquisacao;
    private Boolean ativo;

    // Many to one
    private TipoEquipamento tipoEquipamento; // not null (tipoEquipamentoId)

    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Equipamentos id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [descricao] ------------------------

    @Size(max = 100)
    @NotEmpty
    @Column(name = "descricao", nullable = false, unique = true, length = 100)
    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Equipamentos descricao(String descricao) {
        setDescricao(descricao);
        return this;
    }

    // -- [valor] ------------------------

    @Column(name = "valor", precision = 22)
    public Double getValor() {
        return valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public Equipamentos valor(Double valor) {
        setValor(valor);
        return this;
    }

    // -- [dataAquisacao] ------------------------

    @Column(name = "data_aquisacao", length = 10)
    @Temporal(DATE)
    public Date getDataAquisacao() {
        return dataAquisacao;
    }

    public void setDataAquisacao(Date dataAquisacao) {
        this.dataAquisacao = dataAquisacao;
    }

    public Equipamentos dataAquisacao(Date dataAquisacao) {
        setDataAquisacao(dataAquisacao);
        return this;
    }

    // -- [ativo] ------------------------

    @Column(name = "ativo", length = 0)
    public Boolean getAtivo() {
        return ativo;
    }

    public void setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }

    public Equipamentos ativo(Boolean ativo) {
        setAtivo(ativo);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Equipamentos.tipoEquipamentoId ==> TipoEquipamento.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "tipo_equipamento_id", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE })
    public TipoEquipamento getTipoEquipamento() {
        return tipoEquipamento;
    }

    /**
     * Set the {@link #tipoEquipamento} without adding this Equipamentos instance on the passed {@link #tipoEquipamento}
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link TipoEquipamento}
     */
    public void setTipoEquipamento(TipoEquipamento tipoEquipamento) {
        this.tipoEquipamento = tipoEquipamento;
    }

    public Equipamentos tipoEquipamento(TipoEquipamento tipoEquipamento) {
        setTipoEquipamento(tipoEquipamento);
        return this;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Equipamentos && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getDescricao());
        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warn("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this Equipamentos instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Equipamentos_.id.getName(), getId()) //
                .add(Equipamentos_.descricao.getName(), getDescricao()) //
                .add(Equipamentos_.valor.getName(), getValor()) //
                .add(Equipamentos_.dataAquisacao.getName(), getDataAquisacao()) //
                .add(Equipamentos_.ativo.getName(), getAtivo()) //
                .toString();
    }
}