/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package br.com.aj2.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import br.com.aj2.domain.TipoEquipamento;

@StaticMetamodel(Equipamentos.class)
public abstract class Equipamentos_ {

    // Raw attributes
    public static volatile SingularAttribute<Equipamentos, Integer> id;
    public static volatile SingularAttribute<Equipamentos, String> descricao;
    public static volatile SingularAttribute<Equipamentos, Double> valor;
    public static volatile SingularAttribute<Equipamentos, Date> dataAquisacao;
    public static volatile SingularAttribute<Equipamentos, Boolean> ativo;

    // Many to one
    public static volatile SingularAttribute<Equipamentos, TipoEquipamento> tipoEquipamento;
}