/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package br.com.aj2.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import br.com.aj2.domain.Equipamentos;

@StaticMetamodel(Estudios.class)
public abstract class Estudios_ {

    // Raw attributes
    public static volatile SingularAttribute<Estudios, Integer> id;
    public static volatile SingularAttribute<Estudios, String> nome;
    public static volatile SingularAttribute<Estudios, Boolean> ativo;

    // Many to many
    public static volatile ListAttribute<Estudios, Equipamentos> equipamentos;
}