/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/EntityMeta_.e.vm.java
 */
package br.com.aj2.domain;

import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import br.com.aj2.domain.Cliente;
import br.com.aj2.domain.ItensOs;
import br.com.aj2.domain.Produtor;
import br.com.aj2.enumTypes.FormaPagamento;
import br.com.aj2.enumTypes.StatusOs;

@StaticMetamodel(Os.class)
public abstract class Os_ {

    // Raw attributes
    public static volatile SingularAttribute<Os, Integer> id;
    public static volatile SingularAttribute<Os, StatusOs> status;
    public static volatile SingularAttribute<Os, Date> dataAtendimento;
    public static volatile SingularAttribute<Os, Date> dataConclusao;
    public static volatile SingularAttribute<Os, Date> dataVenciemento;
    public static volatile SingularAttribute<Os, FormaPagamento> formaPagamento;
    public static volatile SingularAttribute<Os, Date> creationDate;
    public static volatile SingularAttribute<Os, String> lastModificationAuthor;
    public static volatile SingularAttribute<Os, Date> lastModificationDate;
    public static volatile SingularAttribute<Os, String> creationAuthor;
    public static volatile SingularAttribute<Os, String> description;
    public static volatile SingularAttribute<Os, Double> total;

    // Many to one
    public static volatile SingularAttribute<Os, Cliente> cliente;
    public static volatile SingularAttribute<Os, Produtor> produtor;

    // One to many
    public static volatile ListAttribute<Os, ItensOs> listItensOs;
}