/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/converter/JsfConverter.e.vm.java
 */
package br.com.aj2.web.converter;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.domain.Equipamentos;
import br.com.aj2.repository.EquipamentosRepository;
import br.com.aj2.web.converter.GenericJsfConverter;

/**
 * JSF converter for {@link Equipamentos}.
 * @see GenericJsfConverter
 */
@Named
@Singleton
public class EquipamentosJsfConverter extends GenericJsfConverter<Equipamentos, Integer> {
    @Inject
    public EquipamentosJsfConverter(EquipamentosRepository equipamentosRepository) {
        super(equipamentosRepository, Equipamentos.class, Integer.class);
    }
}