/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/converter/JsfConverter.e.vm.java
 */
package br.com.aj2.web.converter;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.domain.Servicos;
import br.com.aj2.repository.ServicosRepository;
import br.com.aj2.web.converter.GenericJsfConverter;

/**
 * JSF converter for {@link Servicos}.
 * @see GenericJsfConverter
 */
@Named
@Singleton
public class ServicosJsfConverter extends GenericJsfConverter<Servicos, Integer> {
    @Inject
    public ServicosJsfConverter(ServicosRepository servicosRepository) {
        super(servicosRepository, Servicos.class, Integer.class);
    }
}