/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/converter/JsfConverter.e.vm.java
 */
package br.com.aj2.web.converter;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.domain.TipoEquipamento;
import br.com.aj2.repository.TipoEquipamentoRepository;
import br.com.aj2.web.converter.GenericJsfConverter;

/**
 * JSF converter for {@link TipoEquipamento}.
 * @see GenericJsfConverter
 */
@Named
@Singleton
public class TipoEquipamentoJsfConverter extends GenericJsfConverter<TipoEquipamento, Integer> {
    @Inject
    public TipoEquipamentoJsfConverter(TipoEquipamentoRepository tipoEquipamentoRepository) {
        super(tipoEquipamentoRepository, TipoEquipamento.class, Integer.class);
    }
}