/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Account;
import br.com.aj2.domain.Account_;
import br.com.aj2.repository.AccountRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.AccountPermission;

/**
 * Stateless controller for {@link Account} conversation start. 
 */
@Named
@Singleton
public class AccountController extends GenericController<Account, Integer> {
    private static final String editUri = "/domain/accountEdit.faces";
    private static final String selectUri = "/domain/accountSelect.faces";

    @Inject
    public AccountController(AccountRepository accountRepository, AccountPermission accountPermission) {
        super(accountRepository, accountPermission, selectUri, editUri);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        searchParameters.orderBy(Account_.email);
        return searchParameters;
    }

}