/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import br.com.aj2.domain.Agenda;
import br.com.aj2.repository.AgendaRepository;
import br.com.aj2.web.domain.support.GenericEditForm;
import br.com.aj2.web.faces.ConversationContextScoped;
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Date;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

/**
 * View Helper/Controller to edit {@link Agenda}.
 */
@Named
@ConversationContextScoped
public class AgendaEditForm extends GenericEditForm<Agenda, Integer> {

    @Inject
    public AgendaEditForm(AgendaRepository agendaRepository) {
        super(agendaRepository);
    }

    /**
     * The entity to edit/view.
     */
    public Agenda getAgenda() {
        return getEntity();
    }
    public void fileUpload(FileUploadEvent event) throws IOException{
        try{
            //Instância objetos
            String url = FacesContext.getCurrentInstance().getExternalContext().getRealPath("//resources//file//");  

            //Cria um arquivo UploadFile, para receber o arquivo do evento
            UploadedFile arq = event.getFile();
            //Transformar a imagem em bytes para salvar em banco de dados
            byte[] bimagem = event.getFile().getContents();

            InputStream in = new BufferedInputStream(arq.getInputstream());
            File file = new File(url + "//"+arq.getFileName());
            //O método file.getAbsolutePath() fornece o caminho do arquivo criado
            //Pode ser usado para ligar algum objeto do banco ao arquivo enviado
            String caminho = file.getAbsolutePath();
            getAgenda().setArquivoBinary(bimagem);
            getAgenda().setArquivoFileName(arq.getFileName());
            getAgenda().setArquivoContentType(arq.getContentType());
            FileOutputStream fout = new FileOutputStream(file);
            while(in.available() != 0)
            {
            fout.write(in.read());
            }
            fout.close();

        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        
    }
    public StreamedContent getStreamedContent() {
        return new DefaultStreamedContent(new ByteArrayInputStream(getAgenda().getArquivoBinary()), getAgenda().getArquivoContentType(), getAgenda()
                .getArquivoFileName());
    }
}
