/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.domain.Agenda;
import br.com.aj2.repository.AgendaRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.AgendaPermission;

/**
 * Stateless controller for {@link Agenda} conversation start. 
 */
@Named
@Singleton
public class AgendaController extends GenericController<Agenda, Integer> {
    private static final String editUri = "/domain/agendaEdit.faces";
    private static final String selectUri = "/domain/agendaSelect.faces";

    @Inject
    public AgendaController(AgendaRepository agendaRepository, AgendaPermission agendaPermission) {
        super(agendaRepository, agendaPermission, selectUri, editUri);
    }

}