/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import br.com.aj2.domain.Agenda;
import br.com.aj2.repository.AgendaRepository;
import br.com.aj2.web.converter.AgendaJsfConverter;
import br.com.aj2.web.domain.support.GenericLazyDataModel;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Agenda}
 */
@Named
@ConversationContextScoped
public class AgendaLazyDataModel extends GenericLazyDataModel<Agenda, Integer, AgendaSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public AgendaLazyDataModel(AgendaRepository agendaRepository, AgendaJsfConverter agendaConverter, AgendaController agendaController,
            AgendaSearchForm agendaSearchForm) {
        super(agendaRepository, agendaConverter, agendaController, agendaSearchForm);
    }
}