/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Empresa;
import br.com.aj2.domain.Empresa_;
import br.com.aj2.repository.EmpresaRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.EmpresaPermission;

/**
 * Stateless controller for {@link Empresa} conversation start. 
 */
@Named
@Singleton
public class EmpresaController extends GenericController<Empresa, Integer> {
    private static final String editUri = "/domain/configEdit.faces";
    private static final String selectUri = "/domain/configSelect.faces";

    @Inject
    public EmpresaController(EmpresaRepository empresaRepository, EmpresaPermission empresaPermission) {
        super(empresaRepository, empresaPermission, selectUri, editUri);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        searchParameters.orderBy(Empresa_.email);
        return searchParameters;
    }

}