/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Empresa;
import br.com.aj2.domain.Empresa_;
import br.com.aj2.repository.EmpresaRepository;
import br.com.aj2.web.converter.EmpresaJsfConverter;
import br.com.aj2.web.domain.support.GenericLazyDataModel;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Empresa}
 */
@Named
@ConversationContextScoped
public class EmpresaLazyDataModel extends GenericLazyDataModel<Empresa, Integer, EmpresaSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public EmpresaLazyDataModel(EmpresaRepository empresaRepository, EmpresaJsfConverter empresaConverter, EmpresaController empresaController,
            EmpresaSearchForm empresaSearchForm) {
        super(empresaRepository, empresaConverter, empresaController, empresaSearchForm);
    }

    @Override
    protected void defaultOrder(SearchParameters sp) {
        sp.orderBy(Empresa_.email);
    }
}