/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Equipamentos;
import br.com.aj2.domain.Equipamentos_;
import br.com.aj2.repository.EquipamentosRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.EquipamentosPermission;

/**
 * Stateless controller for {@link Equipamentos} conversation start. 
 */
@Named
@Singleton
public class EquipamentosController extends GenericController<Equipamentos, Integer> {
    private static final String editUri = "/domain/equipamentosEdit.faces";
    private static final String selectUri = "/domain/equipamentosSelect.faces";

    @Inject
    public EquipamentosController(EquipamentosRepository equipamentosRepository, EquipamentosPermission equipamentosPermission) {
        super(equipamentosRepository, equipamentosPermission, selectUri, editUri);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        searchParameters.orderBy(Equipamentos_.descricao);
        return searchParameters;
    }

}