/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Equipamentos;
import br.com.aj2.domain.Equipamentos_;
import br.com.aj2.repository.EquipamentosRepository;
import br.com.aj2.web.converter.EquipamentosJsfConverter;
import br.com.aj2.web.domain.support.GenericLazyDataModel;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Equipamentos}
 */
@Named
@ConversationContextScoped
public class EquipamentosLazyDataModel extends GenericLazyDataModel<Equipamentos, Integer, EquipamentosSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public EquipamentosLazyDataModel(EquipamentosRepository equipamentosRepository, EquipamentosJsfConverter equipamentosConverter,
            EquipamentosController equipamentosController, EquipamentosSearchForm equipamentosSearchForm) {
        super(equipamentosRepository, equipamentosConverter, equipamentosController, equipamentosSearchForm);
    }

    @Override
    protected void defaultOrder(SearchParameters sp) {
        sp.orderBy(Equipamentos_.descricao);
    }
}