/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Grupocliente;
import br.com.aj2.domain.Grupocliente_;
import br.com.aj2.repository.GrupoclienteRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.GrupoclientePermission;

/**
 * Stateless controller for {@link Grupocliente} conversation start. 
 */
@Named
@Singleton
public class GrupoclienteController extends GenericController<Grupocliente, Integer> {
    private static final String editUri = "/domain/grupoclienteEdit.faces";
    private static final String selectUri = "/domain/grupoclienteSelect.faces";

    @Inject
    public GrupoclienteController(GrupoclienteRepository grupoclienteRepository, GrupoclientePermission grupoclientePermission) {
        super(grupoclienteRepository, grupoclientePermission, selectUri, editUri);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        searchParameters.orderBy(Grupocliente_.nome);
        return searchParameters;
    }

}