/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.domain.Locacao;
import br.com.aj2.repository.LocacaoRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.LocacaoPermission;

/**
 * Stateless controller for {@link Locacao} conversation start. 
 */
@Named
@Singleton
public class LocacaoController extends GenericController<Locacao, Integer> {
    private static final String editUri = "/domain/locacaoEdit.faces";
    private static final String selectUri = "/domain/locacaoSelect.faces";

    @Inject
    public LocacaoController(LocacaoRepository locacaoRepository, LocacaoPermission locacaoPermission) {
        super(locacaoRepository, locacaoPermission, selectUri, editUri);
    }

}