/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;
import br.com.aj2.domain.Cliente;
import br.com.aj2.domain.Estudios;
import br.com.aj2.domain.Locacao;
import br.com.aj2.repository.LocacaoRepository;
import br.com.aj2.web.domain.ClienteController;
import br.com.aj2.web.domain.EstudiosController;
import br.com.aj2.web.domain.LocacaoGraphLoader;
import br.com.aj2.web.domain.support.GenericEditForm;
import br.com.aj2.web.domain.support.GenericToOneAssociation;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Locacao}.
 */
@Named
@ConversationContextScoped
public class LocacaoEditForm extends GenericEditForm<Locacao, Integer> {
    @Inject
    protected EstudiosController estudiosController;
    protected GenericToOneAssociation<Estudios, Integer> estudios;
    @Inject
    protected ClienteController clienteController;
    protected GenericToOneAssociation<Cliente, Integer> cliente;

    @Inject
    public LocacaoEditForm(LocacaoRepository locacaoRepository, LocacaoGraphLoader locacaoGraphLoader) {
        super(locacaoRepository, locacaoGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public Locacao getLocacao() {
        return getEntity();
    }

    @PostConstruct
    void setupEstudiossActions() {
        estudios = new GenericToOneAssociation<Estudios, Integer>("locacao_estudios", estudiosController) {
            @Override
            protected Estudios get() {
                return getLocacao().getEstudios();
            }

            @Override
            protected void set(Estudios estudios) {
                getLocacao().setEstudios(estudios);
            }

            @NotNull
            @Override
            public Estudios getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Estudios, Integer> getEstudios() {
        return estudios;
    }

    @PostConstruct
    void setupClientesActions() {
        cliente = new GenericToOneAssociation<Cliente, Integer>("locacao_cliente", clienteController) {
            @Override
            protected Cliente get() {
                return getLocacao().getCliente();
            }

            @Override
            protected void set(Cliente cliente) {
                getLocacao().setCliente(cliente);
            }

            @NotNull
            @Override
            public Cliente getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Cliente, Integer> getCliente() {
        return cliente;
    }
}
