/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.model.LazyDataModel;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.Role;
import br.com.aj2.domain.Role_;
import br.com.aj2.repository.RoleRepository;
import br.com.aj2.web.converter.RoleJsfConverter;
import br.com.aj2.web.domain.support.GenericLazyDataModel;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Role}
 */
@Named
@ConversationContextScoped
public class RoleLazyDataModel extends GenericLazyDataModel<Role, Integer, RoleSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public RoleLazyDataModel(RoleRepository roleRepository, RoleJsfConverter roleConverter, RoleController roleController, RoleSearchForm roleSearchForm) {
        super(roleRepository, roleConverter, roleController, roleSearchForm);
    }

    @Override
    protected void defaultOrder(SearchParameters sp) {
        sp.orderBy(Role_.roleName);
    }
}