/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package br.com.aj2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import br.com.aj2.domain.Servicos;
import br.com.aj2.repository.ServicosRepository;
import br.com.aj2.web.domain.support.GenericController;
import br.com.aj2.web.permission.ServicosPermission;

/**
 * Stateless controller for {@link Servicos} conversation start. 
 */
@Named
@Singleton
public class ServicosController extends GenericController<Servicos, Integer> {
    private static final String editUri = "/domain/servicosEdit.faces";
    private static final String selectUri = "/domain/servicosSelect.faces";

    @Inject
    public ServicosController(ServicosRepository servicosRepository, ServicosPermission servicosPermission) {
        super(servicosRepository, servicosPermission, selectUri, editUri);
    }

}