/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package br.com.aj2.web.domain;

import static br.com.aj2.dao.support.PropertySelector.newPropertySelector;
import javax.inject.Named;
import br.com.aj2.dao.support.PropertySelector;
import br.com.aj2.dao.support.SearchParameters;
import br.com.aj2.domain.TipoEquipamento;
import br.com.aj2.domain.TipoEquipamento_;
import br.com.aj2.web.domain.support.GenericSearchForm;
import br.com.aj2.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link TipoEquipamento}.
 * It exposes a {@link TipoEquipamento} instance so it can be used in search by Example query.
 */
@Named
@ConversationContextScoped
public class TipoEquipamentoSearchForm extends GenericSearchForm<TipoEquipamento, Integer, TipoEquipamentoSearchForm> {
    private static final long serialVersionUID = 1L;

    protected TipoEquipamento tipoEquipamento = new TipoEquipamento();
    protected PropertySelector<TipoEquipamento, String> descricaoSelector = newPropertySelector(TipoEquipamento_.descricao);

    public TipoEquipamento getTipoEquipamento() {
        return tipoEquipamento;
    }

    @Override
    protected TipoEquipamento getEntity() {
        return getTipoEquipamento();
    }

    @Override
    public TipoEquipamentoSearchForm newInstance() {
        return new TipoEquipamentoSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        return new SearchParameters() //
                .anywhere() //
                .property(descricaoSelector) //
        ;
    }

    @Override
    public void resetWithOther(TipoEquipamentoSearchForm other) {
        this.tipoEquipamento = other.getTipoEquipamento();
        this.descricaoSelector = other.getDescricaoSelector();
    }

    // Property selectors
    public PropertySelector<TipoEquipamento, String> getDescricaoSelector() {
        return descricaoSelector;
    }
}
